# Generated by Django 3.2.8 on 2023-01-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_new_project', 'can add new project'), ('dg_view_project', 'OLP can view project')]},
        ),
    ]
